name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1.2', '3.2', '3.3']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    
    - name: Run tests
      run: bundle exec rake spec
    
    - name: Create issue on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `CI Test Failure - Ruby ${{ matrix.ruby-version }}`,
            body: `## Test suite failed for appstage-cli
            
            - **Ruby Version:** ${{ matrix.ruby-version }}
            - **Branch:** ${{ github.ref }}
            - **Commit:** ${{ github.sha }}
            - **Failed Run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            Please investigate the test failures.`,
            labels: ['ci-failure', 'bug']
          })

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.2'
        bundler-cache: true
    
    - name: Build gem
      run: gem build appstage.gemspec
    
    - name: Upload gem artifact
      uses: actions/upload-artifact@v4
      with:
        name: appstage-gem
        path: "*.gem"
        retention-days: 7
    
    - name: Create issue on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'CI Build Failure',
            body: `## Gem build failed for appstage-cli
            
            - **Branch:** ${{ github.ref }}
            - **Commit:** ${{ github.sha }}
            - **Failed Run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            Please investigate the build failure.`,
            labels: ['ci-failure', 'bug']
          })